# This rule is not used by the project spot-instance-training-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the training.training.dcnlab.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: spot-instance-training-operator
    app.kubernetes.io/managed-by: kustomize
  name: provisionedinstance-editor-role
rules:
- apiGroups:
  - training.training.dcnlab.com
  resources:
  - provisionedinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - training.training.dcnlab.com
  resources:
  - provisionedinstances/status
  verbs:
  - get
