# This rule is not used by the project spot-instance-training-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over training.training.dcnlab.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: spot-instance-training-operator
    app.kubernetes.io/managed-by: kustomize
  name: spotinstancejob-admin-role
rules:
- apiGroups:
  - training.training.dcnlab.com
  resources:
  - spotinstancejobs
  verbs:
  - '*'
- apiGroups:
  - training.training.dcnlab.com
  resources:
  - spotinstancejobs/status
  verbs:
  - get
