# This rule is not used by the project spot-instance-training-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to training.training.dcnlab.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: spot-instance-training-operator
    app.kubernetes.io/managed-by: kustomize
  name: spotinstancevm-viewer-role
rules:
- apiGroups:
  - training.training.dcnlab.com
  resources:
  - spotinstancevms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - training.training.dcnlab.com
  resources:
  - spotinstancevms/status
  verbs:
  - get
